name: Deploy Production

on:
  push:
    branches:
      - develop

concurrency:
  group: Default
  cancel-in-progress: false

jobs:
  deploy:
    runs-on:
      - self-hosted
      # - production

    steps:
      - name: Deploy application
        shell: bash
        run: |
          set -e

          cd /home/opc/manga-web

          git fetch origin
          git reset --hard origin/develop
          npm run build

          echo "Fetching source..."
          git fetch origin

          echo "Updating source..."
          git reset --hard origin/develop